#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    sys.path.append(os.path.join(os.getcwd(), os.path.dirname(__file__), '..'))
    from i2b2model.scripts.genconffile import generate_conf_file
    generate_conf_file(sys.argv[1:])
